// <auto-generated />
namespace Loja.Repositorios.SqlServer.EF.CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RenameProdutoEstoque : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameProdutoEstoque));
        
        string IMigrationMetadata.Id
        {
            get { return "201804050034432_RenameProdutoEstoque"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
